version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
  
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:80"

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
